# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 873992cf07fee49661fd05cc963e6ae6b46e1462
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astro/deadnix
    rev: b341adb745fd29075869a52161ae0097ceb7d3a6
    hooks:
      - id: deadnix
        args: [--edit] # Uncomment to automatically modify files
        stages: [commit]
