hostname: localhost
port: 7878
protocol: http
url_base: null
api_key: af19708ea7294869bafbd954a9c3595c
version: 5.11.0.9244
image: lscr.io/linuxserver/radarr
settings:
  media_management:
    rename_movies: true
    replace_illegal_characters: true
    colon_replacement: space-dash-space
    standard_movie_format: '{Movie Title} ({Release Year}) {Quality Full}'
    movie_folder_format: '{Movie Title} ({Release Year})'
    create_missing_movie_folders: false
    delete_empty_folders: false
    skip_free_space_check: false
    minimum_free_space: 100
    use_hardlinks: true
    import_using_script: false
    import_script_path: null
    import_extra_files: false
    unmonitor_deleted_movies: true
    propers_and_repacks: prefer-and-upgrade
    analyze_video_files: true
    rescan_folder_after_refresh: always
    change_file_date: none
    recycling_bin: null
    recycling_bin_cleanup: 7
    set_permissions: false
    chmod_folder: drwxr-xr-x
    chown_group: null
    root_folders:
      delete_unmanaged: false
      definitions: []
  profiles:
    quality_profiles:
      delete_unmanaged: false
      definitions:
        Any:
          upgrades_allowed: false
          qualities:
          - BR-DISK
          - Remux-2160p
          - Bluray-2160p
          - name: WEB 2160p
            members:
            - WEBDL-2160p
            - WEBRip-2160p
          - HDTV-2160p
          - Remux-1080p
          - Bluray-1080p
          - name: WEB 1080p
            members:
            - WEBRip-1080p
            - WEBDL-1080p
          - HDTV-1080p
          - Bluray-720p
          - name: WEB 720p
            members:
            - WEBDL-720p
            - WEBRip-720p
          - HDTV-720p
          - Bluray-576p
          - Bluray-480p
          - name: WEB 480p
            members:
            - WEBDL-480p
            - WEBRip-480p
          - DVD-R
          - DVD
          - SDTV
          - DVDSCR
          - REGIONAL
          - TELECINE
          - TELESYNC
          - CAM
          - WORKPRINT
          upgrade_until_quality: null
          minimum_custom_format_score: 0
          upgrade_until_custom_format_score: 0
          custom_formats: []
          language: english
        SD:
          upgrades_allowed: false
          qualities:
          - Bluray-576p
          - Bluray-480p
          - name: WEB 480p
            members:
            - WEBDL-480p
            - WEBRip-480p
          - DVD
          - SDTV
          - DVDSCR
          - REGIONAL
          - TELECINE
          - TELESYNC
          - CAM
          - WORKPRINT
          upgrade_until_quality: null
          minimum_custom_format_score: 0
          upgrade_until_custom_format_score: 0
          custom_formats: []
          language: english
        HD-720p:
          upgrades_allowed: false
          qualities:
          - Bluray-720p
          - name: WEB 720p
            members:
            - WEBDL-720p
            - WEBRip-720p
          - HDTV-720p
          upgrade_until_quality: null
          minimum_custom_format_score: 0
          upgrade_until_custom_format_score: 0
          custom_formats: []
          language: english
        HD-1080p:
          upgrades_allowed: false
          qualities:
          - Remux-1080p
          - Bluray-1080p
          - name: WEB 1080p
            members:
            - WEBRip-1080p
            - WEBDL-1080p
          - HDTV-1080p
          upgrade_until_quality: null
          minimum_custom_format_score: 0
          upgrade_until_custom_format_score: 0
          custom_formats: []
          language: english
        Ultra-HD:
          upgrades_allowed: false
          qualities:
          - Remux-2160p
          - Bluray-2160p
          - name: WEB 2160p
            members:
            - WEBDL-2160p
            - WEBRip-2160p
          - HDTV-2160p
          upgrade_until_quality: null
          minimum_custom_format_score: 0
          upgrade_until_custom_format_score: 0
          custom_formats: []
          language: english
        HD - 720p/1080p:
          upgrades_allowed: false
          qualities:
          - Remux-1080p
          - Bluray-1080p
          - name: WEB 1080p
            members:
            - WEBRip-1080p
            - WEBDL-1080p
          - HDTV-1080p
          - Bluray-720p
          - name: WEB 720p
            members:
            - WEBDL-720p
            - WEBRip-720p
          - HDTV-720p
          upgrade_until_quality: null
          minimum_custom_format_score: 0
          upgrade_until_custom_format_score: 0
          custom_formats: []
          language: english
    delay_profiles:
      definitions:
      - preferred_protocol: usenet-prefer
        usenet_delay: 0
        torrent_delay: 0
        bypass_if_highest_quality: true
        tags: []
      delete_unmanaged: false
  quality:
    trash_id: null
    definitions:
      Unknown:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      WORKPRINT:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      CAM:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      TELESYNC:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      TELECINE:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      REGIONAL:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      DVDSCR:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      SDTV:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      DVD:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      DVD-R:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      WEBDL-480p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      WEBRip-480p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      Bluray-480p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      Bluray-576p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      HDTV-720p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      WEBDL-720p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      WEBRip-720p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      Bluray-720p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      HDTV-1080p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      WEBDL-1080p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      WEBRip-1080p:
        title: null
        min: 0.0
        preferred: 95.0
        max: 100.0
      Bluray-1080p:
        title: null
        min: 0.0
        preferred: null
        max: null
      Remux-1080p:
        title: null
        min: 0.0
        preferred: null
        max: null
      HDTV-2160p:
        title: null
        min: 0.0
        preferred: null
        max: null
      WEBDL-2160p:
        title: null
        min: 0.0
        preferred: null
        max: null
      WEBRip-2160p:
        title: null
        min: 0.0
        preferred: null
        max: null
      Bluray-2160p:
        title: null
        min: 0.0
        preferred: null
        max: null
      Remux-2160p:
        title: null
        min: 0.0
        preferred: null
        max: null
      BR-DISK:
        title: null
        min: 0.0
        preferred: null
        max: null
      Raw-HD:
        title: null
        min: 0.0
        preferred: null
        max: null
  custom_formats:
    delete_unmanaged: false
    definitions: {}
  indexers:
    minimum_age: 0
    retention: 0
    maximum_size: 0
    rss_sync_interval: 30
    delete_unmanaged: false
    definitions: {}
  download_clients:
    delete_unmanaged: false
    definitions: {}
  notifications:
    delete_unmanaged: false
    definitions: {}
  metadata:
    certification_country: us
    emby_legacy:
      enable: false
      movie_metadata: true
    kodi_emby:
      enable: false
      movie_metadata: true
      movie_metadata_url: false
      movie_metadata_language: english
      movie_images: true
      use_movie_nfo: false
      add_collection_name: true
    roksbox:
      enable: false
      movie_metadata: true
      movie_images: true
    wdtv:
      enable: false
      movie_metadata: true
      movie_images: true
  tags:
    definitions: []
  general:
    host:
      bind_address: '*'
      port: 7878
      ssl_port: 9898
      use_ssl: false
      ssl_cert_path: null
      ssl_cert_password: null
      url_base: /crackshack.io
      instance_name: Radarr
    security:
      authentication: basic
      authentication_required: local-disabled
      username: admin
      password: qskmjjfiG4SdLoxhgTvmJo4RSgBlJA9rpDl8Je2VAvw=
      certificate_validation: local-disabled
    proxy:
      enable: false
      proxy_type: http
      hostname: null
      port: 8080
      username: null
      password: null
      ignored_addresses: []
      bypass_proxy_for_local_addresses: true
    logging:
      log_level: DEBUG
    analytics:
      send_anonymous_usage_data: true
    updates:
      branch: master
      automatic: false
      mechanism: builtin
      script_path: null
    backup:
      folder: Backups
      interval: 7
      retention: 28
  ui:
    first_day_of_week: sunday
    week_column_header: month-first
    runtime_format: hours-minutes
    short_date_format: word-month-first
    long_date_format: month-first
    time_format: twelve-hour
    show_relative_dates: true
    theme: dark
    enable_color_impaired_mode: false
    movie_info_language: english
    ui_language: english

