{ config, lib, pkgs, ... }: {
  environment.systemPackages = builtins.attrValues {
    inherit (pkgs)
      aichat alejandra android-tools anki apktool bc bindfs black blueman
      bottles brightnessctl btop burpsuite cabal-install cargo cliphist
      code-cursor coreutils curl deadnix direnv;
  };
}
#       alacritty
#       alejandra
#       android-tools
#     anki
#     apktool
#     bc
#     bindfs
#     black
#     blueman
#     bottles
#     brightnessctl
#     btop
#     burpsuite
#     cabal-install
#     cabextract
#     cargo
#     cliphist
#     code-cursor
#     coreutils
#     curl
#     deadnix
#     direnv
#     dunst
#     exploitdb
#     fdupes
#     ffmpeg
#     ffmpegthumbnailer
#     file
#     foot
#     fuse
#     gcc
#     gh
#     ghc
#     git
#     glow
#     gnumake
#     google-chrome
#     hashcat
#     haskell-language-server
#     haskellPackages.cabal-fmt
#     hyprshot
#     imagemagick
#     isort
#     jadx
#     john
#     jsbeautifier
#     kanshi
#     kmod
#     libnotify
#     libvirt
#     light
#     literate
#     lsb-release
#     mako
#     manix
#     metasploit
#     mokutil
#     moreutils
#     mpv
#     neovim
#     networkmanagerapplet
#     nil
#     nix-direnv
#     nix-init
#     nix-output-monitor
#     nix-prefetch-github
#     nixd
#     nixpkgs-fmt
#     nmap
#     obsidian
#     openvpn
#     ormolu
#     p7zip
#     pamixer
#     pavucontrol
#     pciutils
#     pipenv
#     pipx
#     playerctl
#     polkit
#     poppler
#     poppler_utils
#     pre-commit
#     pup
#     qemu
#     qimgv
#     quickemu
#     realesrgan-ncnn-vulkan
#     rofi-wayland
#     rust-analyzer
#     rustc
#     shellcheck
#     shfmt
#     slurp
#     snowfallorg.flake
#     socat
#     spacenavd
#     sqlmap
#     stack
#     stegseek
#     swtpm
#     swww
#     texliveTeTeX
#     tmux
#     unionfs-fuse
#     unzip
#     uv
#     vdhcoapp
#     veracrypt
#     viu
#     waybar
#     wget
#     wine
#     winetricks
#     wl-clipboard
#     wlsunset
#     wofi
#     wordlists
#     xdg-utils
#     zip
#     zoxide
#     alejandra
#     direnv
#     git
#     gh
#     inotify-tools
#     nix-direnv
#     nix-output-monitor
#     parallel
#     mdbook
#     pandoc
#     shellcheck
#     pre-commit
#     btop
#       shfmt
#       manix
#     deadnix
#     ;
#   };
# }
